name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Génère tous les jours à minuit
  workflow_dispatch: # Permet de lancer manuellement

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: yasminefhr1
          svg_out_path: dist/github-contribution-grid-snake.svg
      - name: Commit & Push
        uses: actions/upload-artifact@v2
        with:
          name: snake-animation
          path: dist/github-contribution-grid-snake.svg
